filebeat.prospectors: []
filebeat.modules:
  path: /etc/filebeat/modules.d/*.yml
  reload.enabled: false
filebeat.config.prospectors:
  enabled: true
  path: /etc/filebeat/conf.d/*.yml
filebeat.registry_file: /var/log/containers/filebeat_registry
logging.files:
  path: "/etc/filebeat/log"
logging.level: ${LOG_LEVEL}
output.logstash:
  enabled: true
  hosts: ["${LOGSTASH_HOSTS}"]
  index: "${INDEX_PREFIX}"
  loadbalance: true
  pipelining: 0
  save_topology: false
  ssl:
    certificate_authorities: ["/etc/filebeat/logstash-beats.crt"]
setup.kibana:
    host: "${LOGSTASH_HOSTS}"

# metricbeat.modules:
# - module: jolokia
#   metricsets: ["jmx"]
#   enabled: true
#   period: 10s
#   namespace: "jolokia_metrics"
#   hosts: ["resanet-tp-00:8000"]
#   jmx.mappings:
#     - mbean: 'java.lang:type=Runtime'
#       attributes:
#         - attr: Uptime
#           field: uptime
#     - mbean: 'java.lang:type=GarbageCollector,name=ConcurrentMarkSweep'
#       attributes:
#         - attr: CollectionTime
#           field: gc.cms_collection_time
#         - attr: CollectionCount
#           field: gc.cms_collection_count
#     - mbean: 'java.lang:type=Memory'
#       attributes:
#         - attr: HeapMemoryUsage
#           field: memory.heap_usage
#         - attr: NonHeapMemoryUsage
#           field: memory.non_heap_usage
