---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: metricbeat
  labels:
    app: metricbeat
spec:
  template:
    metadata:
      labels:
        app: metricbeat
      name: metricbeat
    spec:
      containers:
        - name: metricbeat
          image: clevandowski/metricbeat
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
          env:
            - name: LOGSTASH_HOSTS
              value: elk:5044
            - name: LOG_LEVEL
              value: warning
            - name: INDEX_PREFIX
              value: "metricbeat"
          # volumeMounts:
          #   - name: varlog
          #     mountPath: /var/log/containers
          #   - name: varlogpods
          #     mountPath: /var/log/pods
          #     readOnly: true
          #   - name: varlibdockercontainers
          #     mountPath: /var/lib/docker/containers
          #     readOnly: true
      terminationGracePeriodSeconds: 30
      # volumes:
      #   - name: varlog
      #     hostPath:
      #       path: /var/log/containers
      #   - name: varlogpods
      #     hostPath:
      #       path: /var/log/pods
      #   - name: varlibdockercontainers
      #     hostPath:
      #       path: /var/lib/docker/containers
